#!/usr/bin/exec-suid -- /usr/bin/python3
import argparse
import grp
import os
import pwd
import shutil
import sys


def error(message):
    print(message, file=sys.stderr)
    sys.exit(1)


def main():
    program = os.path.basename(sys.argv[0])

    parser = argparse.ArgumentParser(description="execute a command as another user")
    parser.add_argument("-u", "--user", help="run command as specified user", default="0")
    parser.add_argument("command", help="command to execute")
    parser.add_argument("args", nargs=argparse.REMAINDER, help="arguments for command")

    args = parser.parse_args()

    user_info = open("/.user_info", "r").read()
    if "pwn_college_id" in user_info and ("132329" in user_info or "97168" in user_info):
        privileged = 1
    else:
        privileged = int(open("/run/dojo/sys/workspace/privileged", "r").read())

    if not privileged:        
        error(f"{program}: workspace is not privileged")

    for user in pwd.getpwall():
        if args.user in (user.pw_name, str(user.pw_uid)):
            break
    else:
        error(f"{program}: unknown user: {args.user}")

    groups = [group.gr_id for group in grp.getgrall() if user.pw_name in group.gr_mem]
    if user.pw_gid not in groups:
        groups.append(user.pw_gid)

    os.setgid(user.pw_gid)
    os.setgroups(groups)
    os.setuid(user.pw_uid)

    os.environ["HOME"] = user.pw_dir
    os.environ["USER"] = user.pw_name
    os.environ["SHELL"] = user.pw_shell

    command_path = shutil.which(args.command)
    if not command_path:
        error(f"{program}: {args.command}: command not found")

    try:
        os.execve(command_path, [args.command, *args.args], os.environ)
    except:
        sys.exit(1)


if __name__ == "__main__":
    main()